# Generated by Django 4.2.21 on 2025-05-29 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('equipments', models.ManyToManyField(to='workout.equipment')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseMuscle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('public', models.BooleanField(db_index=True, default=False)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('estimated_time', models.PositiveIntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('public', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutExercise',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveSmallIntegerField()),
                ('duration', models.PositiveSmallIntegerField(null=True)),
                ('reps', models.PositiveSmallIntegerField(null=True)),
                ('weight', models.PositiveSmallIntegerField(null=True)),
                ('sets', models.PositiveSmallIntegerField(default=1)),
                ('rest', models.PositiveSmallIntegerField(default=120)),
                ('notes', models.TextField(blank=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.exercise')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.workout')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='workout',
            name='exercises',
            field=models.ManyToManyField(through='workout.WorkoutExercise', to='workout.exercise'),
        ),
        migrations.CreateModel(
            name='PlanWorkout',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day', models.PositiveSmallIntegerField()),
                ('notes', models.TextField(blank=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.plan')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workout.workout')),
            ],
        ),
        migrations.AddField(
            model_name='plan',
            name='workouts',
            field=models.ManyToManyField(through='workout.PlanWorkout', to='workout.workout'),
        ),
        migrations.CreateModel(
            name='Muscle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('exercises', models.ManyToManyField(through='workout.ExerciseMuscle', to='workout.exercise')),
            ],
        ),
        migrations.AddField(
            model_name='exercisemuscle',
            name='muscle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.muscle'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='muscles',
            field=models.ManyToManyField(through='workout.ExerciseMuscle', to='workout.muscle'),
        ),
        migrations.AddConstraint(
            model_name='workoutexercise',
            constraint=models.CheckConstraint(check=models.Q(('duration__isnull', False), ('reps__isnull', False), _connector='OR'), name='workout_either_duration_or_reps_notnull', violation_error_message='Either duration or reps must be provided'),
        ),
        migrations.AlterUniqueTogether(
            name='workoutexercise',
            unique_together={('workout', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='workout',
            unique_together={('creator', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='plan',
            unique_together={('creator', 'name')},
        ),
    ]
