# Generated by Django 4.2.21 on 2025-05-29 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workout', '0004_plan_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('height', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('weight', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], db_index=True, max_length=10, null=True)),
                ('bmi', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fitness_level', models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], db_index=True, max_length=20, null=True)),
                ('fitness_goal', models.CharField(blank=True, choices=[('lose weight', 'Lose Weight'), ('gain weight', 'Gain Weight'), ('maintain weight', 'Maintain Weight')], db_index=True, max_length=20, null=True)),
                ('frontend_settings', models.JSONField(default=dict)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.equipment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='userinfo',
            constraint=models.CheckConstraint(check=models.Q(('age__lte', 100)), name='age_lte_100'),
        ),
        migrations.AddConstraint(
            model_name='userinfo',
            constraint=models.CheckConstraint(check=models.Q(('age__gte', 13)), name='age_gte_13'),
        ),
        migrations.AddConstraint(
            model_name='userinfo',
            constraint=models.CheckConstraint(check=models.Q(('height__lte', 200)), name='height_lte_200'),
        ),
        migrations.AddConstraint(
            model_name='userinfo',
            constraint=models.CheckConstraint(check=models.Q(('weight__lte', 200)), name='weight_lte_200'),
        ),
        migrations.AlterUniqueTogether(
            name='userequipment',
            unique_together={('user', 'equipment')},
        ),
    ]
