# Generated by Django 4.2.21 on 2025-06-03 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, default=25, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='bio',
            field=models.TextField(blank=True, default='Welcome! Remember, every journey begins with a single step.'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='fitness_goal',
            field=models.CharField(blank=True, choices=[('lose weight', 'Lose Weight'), ('gain weight', 'Gain Weight'), ('maintain weight', 'Maintain Weight')], db_index=True, default='lose weight', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='fitness_level',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], db_index=True, default='beginner', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='height',
            field=models.PositiveSmallIntegerField(blank=True, default=175, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='weight',
            field=models.PositiveSmallIntegerField(blank=True, default=70, null=True),
        ),
    ]
